import {alphabet} from "../consts/alphabet.const";

export enum AlphabetEnum {
    A = alphabet.A,
    B = alphabet.B,
    C = alphabet.C,
    D = alphabet.D,
    E = alphabet.E,
    F = alphabet.F,
    G = alphabet.G,
    H = alphabet.H,
    I = alphabet.I,
    J = alphabet.J,
    K = alphabet.K,
    L = alphabet.L,
    M = alphabet.M,
    N = alphabet.N,
    O = alphabet.O,
    P = alphabet.P,
    Q = alphabet.Q,
    R = alphabet.R,
    S = alphabet.S,
    T = alphabet.T,
    U = alphabet.U,
    V = alphabet.V,
    W = alphabet.W,
    X = alphabet.X,
    Y = alphabet.Y,
    Z = alphabet.Z,
}
